### ISSUE TITLE
[Todo토론방] 6월 1주차

### ISSUE THREAD

**Issue by hidongmin37** [mobi-projects/nail-case-server#26]
6월 시작

**Comment by qushe8r** [comment]
[redis bitmap 자료구조로  조회수 체크하기](https://pine-pie-554.notion.site/Redis-5ab64aeb77bc4267912fc4eddd1e45b1?pvs=4)

docker-compose는
지출 관리를 한 곳에서 하는게 좋을 것 같아서 제프님한테 말씀은 드려놨는데 aws 계정 만들고 나서 올릴까요?

**Comment by nickkies** [comment]
@qushe8r bitmap 좋네요 

찾아보니 

```java
public class RedisService {
    private final RedisTemplate<byte[], byte[]> redisTemplate;

    public RedisService(RedisTemplate<byte[], byte[]> redisTemplate) {
        this.redisTemplate = redisTemplate;
    }

    public Long countBits(byte[] key) {
        RedisConnection connection = redisTemplate.getConnectionFactory().getConnection();
        return connection.bitCount(key);
    }

    public Long countBitsInRange(byte[] key, long start, long end) {
        RedisConnection connection = redisTemplate.getConnectionFactory().getConnection();
        return connection.bitCount(key, start, end);
    }
}
```

이렇게 하면 될 거 같은데요?

**Comment by qushe8r** [comment]
[API 초안](https://pine-pie-554.notion.site/api-0a5bf26194974e2e9ceae4a98f6a4744?pvs=4)
프론트에서 api 문서 / type 같은 것들 때문에 요청이 들어와서 초안 작성해봤습니다.
변경이나 수정도 가능하니 보시고 말씀해주세요.
초안이긴 하지만 조율을 위해 내일 점심 지나서 제프님이랑 같이 이야기 해볼 예정입니다. ( 내일 점심까지 초안 보여드린다고 말만 해둔 상태 )

**Comment by dongminjang24** [comment]
이거 제가 이제 확인했네요 올라온지도 모르고,, 제프님하고 얘기 해보셨을까요??

**Comment by qushe8r** [comment]
아직이요 ㅎㅎ 이제 보시고 계실 것 같아요

**Comment by dongminjang24** [comment]
아하 빨간 질문들은 프론트 쪽하고 얘기하실때 질문이신거죠?? 제가 답변 작성하고 있었네요

**Comment by qushe8r** [comment]
네 프론트나 디자인 쪽에 물어볼 거긴 한데 의견 남기셔도 괜찮습니다.

**Comment by dongminjang24** [comment]
1. 노티스 관련해서는 응답을 다줘도 될것 같은데,, 노티스 보여주는게 많을까요? 최신 몇개만 보여주는 거 아닌가 싶네요
2. 응답할때는 응답할때 댓글까지 다주는 것보다 클릭했을때 다주는 게 좋지 않을까요?? 댓글이 많아지면 좀 느려질 수도 있을 것 같아서요
3. 샵 생성시 기본 영업시간 테이블 생성하고 → PUT으로 수정만 할 수 있게 하는건 어떤가요? ---> 이부분은 저도 동감합니당 ㅎㅎ
4. 대댓글관련해서는 유튜브처럼 태그식으로 하고 한 댓글에 여러댓글 있는 식으로 하면 좋을 것 같아요
5.커버 이미지는 언제 응답 하는게 좋을까요?  - 내 샵 정보와 함께가 좋지 않을까용?
6.  썸네일이 필요한가요? -> 검색할때 어떻게 나오냐 가 중요할 것 같은데, 나중에는 썸네일 필요하지 않을까요? 결국에?
7. 대표 사진은 한 장인가요? -> 대표사진은 한장이 괜찮지 않을까요??

일단은 이렇게 했는데 이따가 프론트팀하고 얘기하실때 잠깐 참관해도 괜찮을까요? 제가 도움이 된다라면? ㅎㅎ

**Comment by qushe8r** [comment]
네 얘기할때 같이 전달하겠습니다

**Comment by qushe8r** [comment]
저희 Customer랑 NailArtist가 User를 상속해야 할 것 같은데
패키지 구조는 어떻게 할까요?

**Comment by nickkies** [comment]
예전에 회의할때 컨트롤러끼리 서비스끼리 묶자고 했던거 같아요, 그리고 상속하면 말고 일대일 조인은 여려울까요?
+ 내일 거의 확정이면 회의하고 각자 로직 맡아서 시작해도 좋을 것 같어요!

**Comment by dongminjang24** [comment]
일대일 조인도 좋기는 한데 나중에 확장성 면에서 어렵지는 않을까요???

**Comment by dongminjang24** [comment]
아니면 내일 회의를 잠깐할까요??

**Comment by nickkies** [comment]
넹 좋습니다 내일 일정 없어서 아무때나 가능합니다!

**Comment by qushe8r** [comment]
저는 시간 괜찮아요
1:1 조인으로 하는게 더 편할 수도 있을 것 같기도하고요?
찾아보니까 dtype 쓰면 customer에서 artist로 변경해야 할 때 좀 불편하다고 합니다

**Comment by dongminjang24** [comment]
아하 그렇군요,,, 내일 그러면 오후에 2시나 3시에 시간 괜찮으신가요??

**Comment by nickkies** [comment]
넹 그때 괜찮습니다

**Comment by qushe8r** [comment]
```shell
CLOUD_AWS_CREDENTIALS_ACCESS_KEY={{ secrets.AWS_BACKEND_ACCESS_KEY }} \
CLOUD_AWS_CREDENTIALS_SECRET_KEY={{ secrets.AWS_BACKEND_SECRET_KEY }} \
CLOUD_AWS_S3_ENDPOINT=https://s3.ap-northeast-2.amazonaws.com \
nohup ./gradlew bootRun &
```
이렇게 쓰면 될 것 같은데 하고 안되면 이 시간에 컨트롤할 자신이 없어서 댓글로 남겨봅니다.

**Comment by dongminjang24** [comment]
한번 해볼게용

**Comment by dongminjang24** [comment]
@qushe8r 액세스키랑 시크릿키는 그러면 환경변수 저장된건가요?
